# =============================================================
# agent/nodes/rca_writer.py
# Node 4 — Formats the diagnosis into a structured RCA report.
#
# Input:  state["alert_parsed"], state["diagnosis"],
#         state["confidence_score"], state["runbook_source"]
# Output: state["rca_report"]
#
# Why this exists:
#   Raw LLM output is free-form. SRE teams need consistent,
#   structured RCA documents for post-mortems and ServiceNow.
# =============================================================

import logging
from datetime import datetime, timezone
from agent.state import AgentState

logger = logging.getLogger(__name__)

# Confidence thresholds for human-readable labels
CONFIDENCE_LABELS = {
    (0.85, 1.01): "High",
    (0.60, 0.85): "Medium",
    (0.00, 0.60): "Low — Human Review Required",
}


def confidence_label(score: float) -> str:
    """Convert a 0.0-1.0 confidence score to a human-readable label."""
    for (low, high), label in CONFIDENCE_LABELS.items():
        if low <= score < high:
            return label
    return "Unknown"


def severity_to_priority(severity: str) -> str:
    """Map severity string to SRE priority label."""
    mapping = {
        "P1": "P1 — Critical (immediate response required)",
        "P2": "P2 — High (respond within 30 minutes)",
        "P3": "P3 — Medium (respond within 4 hours)",
    }
    return mapping.get(severity.upper(), severity)


def write_rca(state: AgentState) -> AgentState:
    """
    LangGraph Node 4 — RCA Writer.

    Reads:  state["alert_parsed"], state["diagnosis"],
            state["confidence_score"], state["runbook_source"]
    Writes: state["rca_report"]

    Args:
        state: Current AgentState with diagnosis populated

    Returns:
        Updated AgentState with rca_report filled in.
    """
    alert      = state["alert_parsed"]
    diagnosis  = state.get("diagnosis", "No diagnosis available")
    confidence = state.get("confidence_score", 0.0)
    runbook    = state.get("runbook_source", "none")
    error      = state.get("error")

    logger.info(f"[Node 4] Writing RCA report for alert: {alert['alert_name']}")

    # Timestamp in UTC (standard for SRE incident docs)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Build warning banner if confidence is low
    confidence_warning = ""
    if confidence < 0.60:
        confidence_warning = (
            "\n> ⚠️ **LOW CONFIDENCE** — AI diagnosis confidence is below 60%. "
            "This report requires human review before action.\n"
        )

    # Build error note if diagnosis failed
    error_note = ""
    if error:
        error_note = f"\n> ❌ **Error during diagnosis:** `{error}`\n"

    # Format the RCA report in standard SRE markdown template
    rca_report = f"""# Root Cause Analysis (AI-Generated)

> Generated by SRE AI Agent | {timestamp}
> Confidence: {confidence:.0%} ({confidence_label(confidence)}){confidence_warning}{error_note}

---

## Incident Summary

| Field          | Value                                      |
|----------------|--------------------------------------------|
| Alert          | {alert['alert_name']}                      |
| Priority       | {severity_to_priority(alert['severity'])}  |
| Service        | {alert['service']}                         |
| Alert Type     | {alert['alert_type']}                      |
| Generated At   | {timestamp}                                |
| Runbook Used   | {runbook}                                  |
| AI Confidence  | {confidence:.0%} ({confidence_label(confidence)}) |

---

## Alert Message

> {alert['message']}

---

## Diagnosis

{diagnosis}

---

## Runbook Reference

Relevant runbook retrieved: **`{runbook}`**
Full runbooks available at: `docs/runbooks/`

---

## Next Steps

1. Review the immediate steps listed in the Diagnosis section above
2. Validate findings against live Datadog metrics and logs
3. Execute remediation steps and monitor recovery
4. Update this RCA with actual root cause once confirmed
5. Create a post-mortem ticket if duration > 30 minutes

---

## Disclaimer

This RCA was generated automatically by the SRE AI Agent using LangGraph + Claude.
It is based on runbook retrieval (RAG) and LLM reasoning.
**Always validate AI-generated diagnoses before executing remediation in production.**
"""

    logger.info(f"[Node 4] RCA report generated ({len(rca_report)} chars)")

    return {
        **state,
        "rca_report": rca_report,
    }